<main class="container">
    <div class="row justify-content-center mb-3">
        <div class="col-md-9">
            <div class="card">
                <div class="card-header bg-transparent" id="headingOne">
                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne"
                            aria-expanded="false" aria-controls="collapseOne">Add new task...
                    </button>
                </div>
                <div id="collapseOne" class="collapse" aria-labelledby="headingOne">
                    <div class="card-body">
                        <form id="new_task" class="needs-validation" novalidate>
                            <div class="form-row">
                                <div class="col-md-6 mb-2">
                                    <label for="validationCustom01">User name</label>
                                    <input type="text" class="form-control" name="username" id="validationCustom01"
                                           required>
                                    <div class="invalid-feedback">Please enter username.</div>
                                </div>
                                <div class="col-md-6 mb-2">
                                    <label for="validationCustom02">Email</label>
                                    <input type="email" class="form-control" name="email" id="validationCustom02"
                                           required>
                                    <div class="invalid-feedback">Please provide a valid email.</div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">Description</label>
                                <textarea class="form-control" name="content" id="exampleFormControlTextarea1" rows="2"
                                          required></textarea>
                                <div class="invalid-feedback">Can't add empty task.</div>
                            </div>
                            <button class="btn btn-primary text-right" type="submit">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-9 mb-3">
            <div id="order" class="dropdown" style="visibility: hidden;">
                <a class="dropdown-toggle" type="button" id="dropMenu" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">Sort by</a>
                <div id="dropdownItemsHolder" class="dropdown-menu" aria-labelledby="dropMenu">
                    <button class="dropdown-item" type="button" data-rule="sa">Status ascending</button>
                    <button class="dropdown-item active" type="button" data-rule="sd">Status descending</button>
                    <button class="dropdown-item" type="button" data-rule="ua">User name ascending</button>
                    <button class="dropdown-item" type="button" data-rule="ud">User name descending</button>
                    <button class="dropdown-item" type="button" data-rule="ea">Email ascending</button>
                    <button class="dropdown-item" type="button" data-rule="ed">Email descending</button>
                </div>
            </div>
        </div>

        <section id="cw" class="cards-wrapper col-md-9 mb-3">
            <div style="text-align: center;">
                <div class="spinner-grow" role="status">
                    <span class="sr-only">Loading...</span>
                </div>
            </div>
        </section>
    </div>
    <nav id="pagination" aria-label="pagination"></nav>
</main>
<!-- Toast -->
<div id="apptoast" class="toast" data-delay="5000">
    <div class="toast-header">
        <strong class="mr-auto">ToDo</strong>
        <small>just now</small>
    </div>
    <div class="toast-body"></div>
</div>
<!-- End Toast -->
<!-- Modal -->
<div class="modal fade" id="loginModal" data-backdrop="static" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Admin</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="col">
                    <div id="validationServer05"></div>
                    <div class="invalid-feedback mb-3">
                        Wrong login or password...
                    </div>
                </div>
                <form id="loginForm" class="needs-validation" novalidate>
                    <div class="mb-3">
                        <input type="text" placeholder="Login" name="login" class="form-control" id="modal_login"
                               required>
                        <div class="invalid-feedback">
                            Please enter login
                        </div>
                    </div>
                    <div class="mb-3">
                        <input type="password" placeholder="Password" name="password" class="form-control"
                               id="modal_password" required>
                        <div class="invalid-feedback">
                            Please enter password
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary float-right" data-target="#loginForm">Log in</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- End Modal -->