<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><?= $this->_title ?></title>
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="theme-color" content="#2a2b30">
    <meta name="description" content="Simple web todo list"/>
    <meta name="keywords" content="tasks, todos, web design"/>
    <meta name="author" content="Boris Shobat <cosmicboris@gmail.com>"/>
    <link rel="shortcut icon" href="/assets/img/favicon.ico" type="image/vnd.microsoft.icon">
    <link rel="stylesheet" href="<?= Config::STYLES_DIR ?>bootstrap.css">
    <link rel="stylesheet" href="<?= Config::STYLES_DIR ?>bootstrap-grid.css">
    <link rel="stylesheet" href="<?= Config::STYLES_DIR ?>bootstrap-reboot.css">
    <link rel="stylesheet" href="<?= Config::STYLES_DIR ?>styles.css">
</head>
<body>
<header class="d-flex d-flex justify-content-between p-3 px-md-4 mb-3 bg-white border-bottom">
    <h3 class="my-0 mr-md-auto font-weight-normal">Tasks</h3>
    <a id="btnLogin" class="btn btn-outline-primary" href="#">_</a>
</header>
<?php
include $this->__body;
?>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script src="/assets/js/main.js" type="module"></script>
</body>
</html>