<?php
use ToDo\core\Config;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><?=$this->_title?></title>
    <link rel="stylesheet" href="<?=Config::STYLES_DIR?>bootstrap.css">
    <link rel="stylesheet" href="<?=Config::STYLES_DIR?>bootstrap-grid.css">
    <link rel="stylesheet" href="<?=Config::STYLES_DIR?>bootstrap-reboot.css">
    <link rel="stylesheet" href="<?=Config::STYLES_DIR?>styles.css">
</head>
<body>
<div class="d-flex d-flex justify-content-between p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h3 class="my-0 mr-md-auto font-weight-normal">Tasks</h3>
    <a id="btnLogin" class="btn btn-outline-primary" href="#"></a>
    <!--data-toggle="modal" data-target="#loginModal"-->
</div>
<!-- Modal -->
<div class="modal fade" id="loginModal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Admin</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="col">
                    <div id="validationServer05"></div>
                    <div class="invalid-feedback mb-3">
                        Wrong login or password...
                    </div>
                </div>
                <form id="loginForm" class="needs-validation" novalidate>
                        <div class="mb-3">
                            <input type="text" placeholder="Login" name="login" class="form-control" id="modal_login" required>
                            <div class="invalid-feedback">
                                Please enter login
                            </div>
                        </div>
                        <div class="mb-3">
                            <input type="password" placeholder="Password" name="password" class="form-control" id="modal_password" required>
                            <div class="invalid-feedback">
                                Please enter password
                            </div>
                        </div>
                    <button type="submit" class="btn btn-primary float-right" data-target="#loginForm">Log in</button>
                </form>
            </div>
        </div>
    </div>
</div>
<?php include_once $this->_page_content;?>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="/js/main.js"></script>
</body>
</html>