<div class="container">
    <div class="row justify-content-center mb-3">
        <div class="col-md-9">
            <div class="card">
                    <div class="card-header bg-transparent" id="headingOne">
                        <h2 class="mb-0">
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                Add new task...
                            </button>
                        </h2>
                    </div>
                    <div id="collapseOne" class="collapse" aria-labelledby="headingOne">
                        <div class="card-body">
                            <form id="new_task" class="needs-validation" novalidate>
                                <div class="form-row">
                                    <div class="col-md-6 mb-2">
                                        <label for="validationCustom01">User name</label>
                                        <input type="text" class="form-control" name="username" id="validationCustom01" required>
                                        <div class="invalid-feedback">
                                            Please enter username.
                                        </div>
                                    </div>
                                    <div class="col-md-6 mb-2">
                                        <label for="validationCustom02">Email</label>
                                        <input type="email" class="form-control" name="email" id="validationCustom02" required>
                                        <div class="invalid-feedback">
                                            Please provide a valid email.
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="exampleFormControlTextarea1">Description</label>
                                    <textarea class="form-control" name="content" id="exampleFormControlTextarea1" rows="2" required></textarea>
                                    <div class="invalid-feedback">
                                        Can't add empty task.
                                    </div>
                                </div>

                                <button class="btn btn-primary text-right" type="submit">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-9 mb-3">
            <div id="order" class="dropdown" style="visibility: hidden;">
                <a class="dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Sort by
                </a>
                <div id="dropdownItemsHolder" class="dropdown-menu" aria-labelledby="dropdownMenu2">
                    <button class="dropdown-item" type="button" data-rule="completed ASC">Status ascending</button>
                    <button class="dropdown-item active" type="button" data-rule="completed DESC">Status descending</button>
                    <button class="dropdown-item" type="button" data-rule="username ASC">User name ascending</button>
                    <button class="dropdown-item" type="button" data-rule="username DESC">User name descending</button>
                    <button class="dropdown-item" type="button" data-rule="email ASC">Email ascending</button>
                    <button class="dropdown-item" type="button" data-rule="email DESC">Email descending</button>
                </div>
            </div>
        </div>

        <section id="cardsWrapper" class="col-md-9 mb-3">
            <div style="position: fixed; top: 0; left: 0; height: 100vh; width: 100vw; display: flex; justify-content: center; align-items: center">
                <div class="spinner-grow" style="width: 3rem; height: 3rem;" role="status">
                    <span class="sr-only">Loading...</span>
                </div>
            </div>
        </section>
    </div>

    <nav id="pagination" aria-label="pagination"></nav>
</div>

<div id="apptoast" class="toast" data-delay="5000" style="position: absolute; top: 5rem; right: 1.5rem; min-width: 14rem">
    <div class="toast-header">
        <strong class="mr-auto">ToDo</strong>
        <small>just now</small>
    </div>
    <div class="toast-body"></div>
</div>